# Generated by Django 5.0.3 on 2024-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_specialization_remove_service_visits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contacts',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
