# Generated by Django 5.0.3 on 2024-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'PLANNED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
