# Generated by Django 5.0.3 on 2024-06-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patient_contact_info_visit_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contacts',
            new_name='contact_info',
        ),
    ]
